# Generated by Django 4.2 on 2023-04-19 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('image', models.ImageField(upload_to='static/img')),
                ('url', models.URLField(blank=True)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
            ],
        ),
    ]
