# Generated by Django 4.2 on 2023-04-19 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enlaces',
            new_name='Enlace',
        ),
    ]
