# Generated by Django 4.2 on 2023-04-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enlaces', '0004_alter_enlace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlace',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
